name: branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: |
          npm run lint
          [ ! -z "$(git status -s | tr -d $'\n')" ] && {
            echo "modified files exist after linting."
            echo "run 'npm run lint' to fix and commit the modified files:"
            echo "---"
            git status -s
            exit 1
          }

      - name: Test
        run: |
          npm run test
